CFLAGS = -Wall -g   

all: diskinfo disklist diskget 

diskinfo: diskinfo.c
	gcc $(CFLAGS) diskinfo.c -o diskinfo

disklist: disklist.c
	gcc $(CFLAGS) disklist.c -o disklist

diskget: diskget.c
	gcc $(CFLAGS) diskget.c -o diskget
